services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    environment:
      - WP_DB=${WP_DB}
      - MARIADB_ADMIN=${MARIADB_ADMIN}
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_ADMIN_PWD=${MARIADB_ADMIN_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
    volumes:
      - "dbdata:/var/lib/mysql"
    networks:
      - docker-network

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      ## Wordpress Access
      - WP_DIR=${WP_DIR}
      - WP_URL=${WP_URL}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      ## Mariadb Access
      - WP_DB=${WP_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
      - MARIADB_HOST=${MARIADB_HOST}
      ## Wordpress User
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    volumes:
      - "wordpress_files:/var/www/wordpress"
    networks:
      - docker-network

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx-conf
    image: nginx
    container_name: nginx
    env_file: .env
    restart: always
    ports:
      - "443:443"
    volumes:
      - "wordpress_files:/var/www/wordpress"
    networks:
      - docker-network

volumes:
  wordpress_files:
  dbdata:

networks:
  docker-network:
    driver: bridge
  
